### ISSUE TITLE
--fabulous-off for ./manage.py test

### ISSUE THREAD

**Issue by arsavard** [hugobast/nosepride#9]
I was wondering: with nosetests the --fabulous-off works, but for ./manage.py test --fabulous-off doesn't. Do you think you might add that eventually or would you accept a merge request if it's tweaked to work with the django too?

**Comment by hugobast** [comment]
I think you have to add that switch to the NOSE_ARGS, otherwise the django runner just ignores it. Does that make sense?

**Comment by arsavard** [comment]
Yes, you're right! I should be pestering django runner folks! Thanks Jebus! :D
